apiVersion: apps/v1
kind: Deployment
metadata:
  name: jacks
spec:
  selector:
    matchLabels:
      app: jacks
  replicas: 1
  template:
    metadata:
      name: jacks
      labels:
        app: jacks
    spec:
      containers:
      - image: quay.io/felicityallen/jacks:0.2.5
        imagePullPolicy: IfNotPresent
        name: jacks
        volumeMounts:
        - name: results
          mountPath: /app/server/results
        env:
        - name: CELERY_BROKER_URL
          value: redis://redis.default.svc.cluster.local:6379/0
        - name: CELERY_RESULT_BACKEND
          value: redis://redis.default.svc.cluster.local:6379/0
        ports:
        - containerPort: 8005
          hostPort: 18005
          name: jacks
          volumes:
        resources:
          requests:
            memory: "256Mi"
            cpu: 1
          limits:
            memory: "2Gi"
            cpu: 2
        livenessProbe:
          httpGet:
            path: /
            port: jacks
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 240
      volumes:
      - name: results
        persistentVolumeClaim:
          claimName: jacks-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      name: redis
      labels:
        app: redis
    spec:
      containers:
      - image: redis
        imagePullPolicy: IfNotPresent
        name: redis
        ports:
        - containerPort: 6379
          name: redis
        resources:
          requests:
            memory: "128Mi"
            cpu: 1
          limits:
            memory: "2Gi"
            cpu: 2
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - redis-cli -h $(hostname) ping
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 240
          successThreshold: 1
          timeoutSeconds: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery
spec:
  selector:
    matchLabels:
      app: celery
  replicas: 1
  template:
    metadata:
      name: celery
      labels:
        app: celery
    spec:
      containers:
      - image: quay.io/felicityallen/jacks:0.2.5
        imagePullPolicy: IfNotPresent
        name: jacks
        volumeMounts:
        - name: results
          mountPath: /app/server/results
        env:
        - name: CELERY_BROKER_URL
          value: redis://redis.default.svc.cluster.local:6379/0
        - name: CELERY_RESULT_BACKEND
          value: redis://redis.default.svc.cluster.local:6379/0
        command: ["celery"]
        args: ["-A", "app.celery", "worker", "-l", "info"]
        resources:
          requests:
            memory: "512Mi"
            cpu: 1
          limits:
            memory: "2Gi"
            cpu: 2
        livenessProbe:
          exec:
            command:
            - "/bin/sh"
            - "-c"
            - "celery status | grep OK"
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 240
          successThreshold: 1
          timeoutSeconds: 1
      volumes:
      - name: results
        persistentVolumeClaim:
          claimName: jacks-pvc
